- src/hs27.jl
> Fix hs27 classification string

- src/curly.jl
> curly: fix x0

- src/AMPGO02.jl
- src/AMPGO03.jl
- src/AMPGO04.jl
- src/AMPGO05.jl
- src/AMPGO06.jl
- src/AMPGO07.jl
- src/AMPGO08.jl
- src/AMPGO09.jl
- src/AMPGO10.jl
- src/AMPGO11.jl
- src/AMPGO12.jl
- src/AMPGO13.jl
- src/AMPGO14.jl
- src/AMPGO15.jl
- src/AMPGO18.jl
- src/AMPGO20.jl
- src/AMPGO21.jl
- src/AMPGO22.jl
- src/Dus2_1.jl
- src/Dus2_3.jl
- src/Dus2_9.jl
- src/Duscube.jl
- src/shpak1.jl
- src/shpak2.jl
- src/shpak3.jl
- src/shpak4.jl
- src/shpak5.jl
- src/shpak6.jl
@Goysa2 You're using 3 spaces for indentation... 😠
> fix syntax and args

- src/ADNLPProblems/hs101.jl
- src/ADNLPProblems/hs102.jl
- src/ADNLPProblems/hs103.jl
- src/PureJuMP/hs101.jl
- src/PureJuMP/hs102.jl
- src/PureJuMP/hs103.jl
- test/runtests.jl
This is an attempt to fix the [unit tests](https://github.com/JuliaSmoothOptimizers/OptimizationProblems.jl/commit/c562568f35b52fd017128f8a1c5f433c01a201ef#commitcomment-57214284)
> Fix problems `hs101`, `hs102`, `hs103`

- Project.toml
@amontoison I missed that the new release failed https://github.com/JuliaRegistries/General/pull/48855
I think this PR should fix the problem.
> Add upper bound

- Project.toml
- src/OptimizationProblems.jl
- test/runtests.jl
- test/utils.jl
#62 
Merge the metadata in a single dataframes. I will add a simple doc in a follow-up PR.
> Add global meta

- docs/src/reference.md
- src/OptimizationProblems.jl
This should fix the documentation failed build
> Add `const` keyword

- docs/make.jl
- docs/src/meta.md
> Add docs for meta

- README.md
- docs/make.jl
- docs/src/contributing.md
- docs/src/index.md
> Add contributing.md with guidelines for new problems

- src/ADNLPProblems/AMPGO13.jl
- src/ADNLPProblems/hs10.jl
- src/ADNLPProblems/hs11.jl
- src/ADNLPProblems/hs14.jl
- src/ADNLPProblems/hs25.jl
- src/ADNLPProblems/lincon.jl
- src/ADNLPProblems/linsv.jl
- src/ADNLPProblems/mgh01feas.jl
- test/runtests.jl
#126 
```
using ADNLPModels, OptimizationProblems, NLPModels
ad_problems = [OptimizationProblems.ADNLPProblems.eval(Symbol(pb))() for pb in setdiff(OptimizationProblems.meta[!, :name], ["hs110"])]
for pb in ad_problems @show pb.meta.name;x = rand(pb.meta.nvar);jac(pb, x);grad(pb, x) end
```
now works.
> Remove `T` to convert vector

- src/ADNLPProblems/woods.jl
- src/PureJuMP/woods.jl
#119 
http://www.cs.cas.cz/matonoha/download/V1081.pdf
> Fix `woods` problem

- src/ADNLPProblems/NZF1.jl
- src/Meta/NZF1.jl
- src/PureJuMP/NZF1.jl
#123 
Because of the `x[i + 19]` term, I think the problem does not make sense for `n < 26`.
> Set minimum number of variables for `NZF1`

- src/ADNLPProblems/BOX2.jl
- src/Meta/BOX2.jl
- src/PureJuMP/BOX2.jl
Box2 variant of #140 from CUTEst
https://bitbucket.org/optrove/sif/src/master/BOX2.SIF
> add box2 problem from cutest

- src/ADNLPProblems/gaussian.jl
- src/Meta/gaussian.jl
- src/PureJuMP/gaussian.jl
Gaussian function from More, Garbow and Hillstrom added for MTH8408
> Added Gaussian fct

- src/ADNLPProblems/clnlbeam.jl
- src/Meta/clnlbeam.jl
- src/PureJuMP/clnlbeam.jl
- test/runtests.jl
> Add `clnlbeam` problem

- src/ADNLPProblems/polygon1.jl
- src/Meta/polygon1.jl
- src/PureJuMP/polygon1.jl
> Add `polygon1`

- src/ADNLPProblems/polygon2.jl
- src/Meta/polygon2.jl
- src/PureJuMP/polygon2.jl
> Add `polygon2`

- src/ADNLPProblems/polygon3.jl
- src/Meta/polygon3.jl
- src/PureJuMP/polygon3.jl
> Add `polygon3`

- src/ADNLPProblems/structural.jl
- src/Meta/structural.jl
- src/PureJuMP/PureJuMP.jl
- src/PureJuMP/structural.jl
> Add `structural`

- src/ADNLPProblems/polygon.jl
- src/Meta/polygon.jl
- src/PureJuMP/polygon.jl
> Add `polygon`

- src/ADNLPProblems/clnlbeam.jl
- src/ADNLPProblems/zangwil3.jl
- src/Meta/zangwil3.jl
- src/PureJuMP/zangwil3.jl
- test/utils.jl
I didn't add the `test_linear_constraints` to the unit test as it will take a lot of time.
> Fix `lin` keyword and add linear constraint check

- docs/src/contributing.md
Before that it was just returning a string with "\n" everywhere...
> up `generate_meta` to get the file directly

- src/PureJuMP/camshape.jl
- src/PureJuMP/triangle.jl
> Add jump cops

- Project.toml
A lot of new problems and fixes.
> Version 0.4.3

- src/ADNLPProblems/genrose.jl
@tmigot about ADNLPProblems.rosenbrock, fixes #208
> fix rosenbrock fixes #208

- Project.toml
With Julia 1.6 and the new linear API
> Version 0.5.0

- src/ADNLPProblems/chain.jl
- src/Meta/chain.jl
- src/PureJuMP/chain.jl
> add `chain` problem

- src/ADNLPProblems/ADNLPProblems.jl
- src/ADNLPProblems/channel.jl
- src/Meta/channel.jl
- src/PureJuMP/channel.jl
> Add channel problem

- src/ADNLPProblems/robotarm.jl
- src/PureJuMP/hovercraft1d.jl
There was some difference between the JuMP and AD models for `hovercraft1d`
> Make only one vcat in `robotarm` and fix `hovercraft1d`

- src/ADNLPProblems/avion2.jl
- src/Meta/avion2.jl
- src/PureJuMP/avion2.jl
https://github.com/mpf/Optimization-Test-Problems/blob/master/cute/avion2.mod
Another generated problem. This is one is large, but still readable.
> Add `avion2`

- src/ADNLPProblems/allinit.jl
- src/ADNLPProblems/allinitc.jl
- src/ADNLPProblems/allinitu.jl
- src/Meta/allinit.jl
- src/Meta/allinitc.jl
- src/Meta/allinitu.jl
- src/PureJuMP/allinit.jl
- src/PureJuMP/allinitc.jl
- src/PureJuMP/allinitu.jl
https://github.com/mpf/Optimization-Test-Problems/blob/master/cute/allinit.mod
https://github.com/mpf/Optimization-Test-Problems/blob/master/cute/allinitc.mod
https://github.com/mpf/Optimization-Test-Problems/blob/master/cute/allinitu.mod
> Add allinit problems

- src/ADNLPProblems/alsotame.jl
- src/Meta/alsotame.jl
- src/PureJuMP/alsotame.jl
https://github.com/mpf/Optimization-Test-Problems/blob/master/cute/alsotame.mod
> Add `alsotame`

- src/ADNLPProblems/aircrfta.jl
- src/Meta/aircrfta.jl
- src/PureJuMP/aircrfta.jl
This is translated from https://github.com/mpf/Optimization-Test-Problems/blob/master/cute/aircrfta.mod
> Add aircrafta

- Project.toml
- src/ADNLPProblems/ADNLPProblems.jl
- src/ADNLPProblems/hs68.jl
- src/ADNLPProblems/hs69.jl
- src/Meta/hs68.jl
- src/Meta/hs69.jl
- src/PureJuMP/PureJuMP.jl
- src/PureJuMP/hs68.jl
- src/PureJuMP/hs69.jl
#113 
https://www.wolframalpha.com/input?i=int_-inf%5Ex+exp%28-y%5E2%2F2%29%2Fsqrt%282pi%29+dy
> Add `hs68` and `hs69`

- src/ADNLPProblems/hs87.jl
- src/Meta/hs87.jl
- src/PureJuMP/hs87.jl
> Add `hs87`

- test/runtests.jl
Simplifying the AD tests as the breakage tests are no longer working, e.g. https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/actions/runs/4016496155
> Refactor test environment

- src/ADNLPProblems/argtrig.jl
- src/ADNLPProblems/bard.jl
- src/ADNLPProblems/biggs5.jl
- src/ADNLPProblems/brownal.jl
- src/ADNLPProblems/broyden3d.jl
- src/Meta/argtrig.jl
- src/Meta/bard.jl
- src/Meta/biggs5.jl
- src/Meta/brownal.jl
- src/Meta/broyden3d.jl
- src/PureJuMP/argtrig.jl
- src/PureJuMP/bard.jl
- src/PureJuMP/biggs5.jl
- src/PureJuMP/brownal.jl
- src/PureJuMP/broyden3d.jl
- test/runtests.jl
> Add problems `argtrig`, `bard`, `biggs5`, `brownal` and `broyden3d`

- src/ADNLPProblems/penalty1.jl
- src/Meta/penalty1.jl
- src/PureJuMP/penalty1.jl
> Add `penalty1`

- src/ADNLPProblems/watson.jl
- src/Meta/watson.jl
- src/PureJuMP/watson.jl
> Add `watson`

- Project.toml
This one only works with ADNLPModels 0.6 as it implements in-place residual and constraints
> Version 0.7.0

- test/runtests.jl
- test/test_utils.jl
Next step will be to reorganize the workflow to avoid instantiating several times the same models
> Regroup tested functionalities in functions

- test/runtests.jl
- test/test_utils.jl
- test/utils.jl
So that we loop once over the problems
> Refactor tests

- src/ADNLPProblems/cragglvy2.jl
- src/Meta/cragglvy2.jl
- src/PureJuMP/chainwoo.jl
- src/PureJuMP/cragglvy2.jl
- src/PureJuMP/genrose.jl
- src/PureJuMP/powellsg.jl
Review the first 4 problems of #116
> Add modified/corrected Cragg and Levy function

- src/ADNLPProblems/bearing.jl
- src/Meta/bearing.jl
- src/PureJuMP/bearing.jl
> Add COPS bearing

- src/ADNLPProblems/marine.jl
- src/Meta/marine.jl
- src/PureJuMP/marine.jl
> Add COPS 3 marine

- src/Meta/bard.jl
- src/Meta/gulf.jl
- src/Meta/watson.jl
- test/runtests.jl
> Fix scalable

- src/ADNLPProblems/hs220.jl
- src/ADNLPProblems/hs221.jl
- src/ADNLPProblems/hs222.jl
- src/ADNLPProblems/hs223.jl
- src/ADNLPProblems/hs224.jl
- src/ADNLPProblems/hs225.jl
- src/Meta/hs220.jl
- src/Meta/hs221.jl
- src/Meta/hs222.jl
- src/Meta/hs223.jl
- src/Meta/hs224.jl
- src/Meta/hs225.jl
- src/PureJuMP/hs220.jl
- src/PureJuMP/hs221.jl
- src/PureJuMP/hs222.jl
- src/PureJuMP/hs223.jl
- src/PureJuMP/hs224.jl
- src/PureJuMP/hs225.jl
> Add HS220 to HS225

- src/ADNLPProblems/hs226.jl
- src/ADNLPProblems/hs227.jl
- src/ADNLPProblems/hs228.jl
- src/ADNLPProblems/hs229.jl
- src/ADNLPProblems/hs230.jl
- src/Meta/hs226.jl
- src/Meta/hs227.jl
- src/Meta/hs228.jl
- src/Meta/hs229.jl
- src/Meta/hs230.jl
- src/PureJuMP/hs226.jl
- src/PureJuMP/hs227.jl
- src/PureJuMP/hs228.jl
- src/PureJuMP/hs229.jl
- src/PureJuMP/hs230.jl
> HS226 to 230

- src/ADNLPProblems/hs261.jl
- src/ADNLPProblems/hs262.jl
- src/ADNLPProblems/hs263.jl
- src/ADNLPProblems/hs264.jl
- src/ADNLPProblems/hs265.jl
- src/Meta/hs261.jl
- src/Meta/hs262.jl
- src/Meta/hs263.jl
- src/Meta/hs264.jl
- src/Meta/hs265.jl
- src/PureJuMP/hs261.jl
- src/PureJuMP/hs262.jl
- src/PureJuMP/hs263.jl
- src/PureJuMP/hs264.jl
- src/PureJuMP/hs265.jl
> HS261 to 265

- src/ADNLPProblems/hs256.jl
- src/ADNLPProblems/hs257.jl
- src/ADNLPProblems/hs258.jl
- src/ADNLPProblems/hs259.jl
- src/ADNLPProblems/hs260.jl
- src/Meta/hs256.jl
- src/Meta/hs257.jl
- src/Meta/hs258.jl
- src/Meta/hs259.jl
- src/Meta/hs260.jl
- src/PureJuMP/hs256.jl
- src/PureJuMP/hs257.jl
- src/PureJuMP/hs258.jl
- src/PureJuMP/hs259.jl
- src/PureJuMP/hs260.jl
> HS256 to 260

- src/ADNLPProblems/hs251.jl
- src/ADNLPProblems/hs252.jl
- src/ADNLPProblems/hs253.jl
- src/ADNLPProblems/hs254.jl
- src/ADNLPProblems/hs255.jl
- src/Meta/hs251.jl
- src/Meta/hs252.jl
- src/Meta/hs253.jl
- src/Meta/hs254.jl
- src/Meta/hs255.jl
- src/PureJuMP/hs251.jl
- src/PureJuMP/hs252.jl
- src/PureJuMP/hs253.jl
- src/PureJuMP/hs254.jl
- src/PureJuMP/hs255.jl
> HS251 to 255

- src/ADNLPProblems/hs231.jl
- src/ADNLPProblems/hs232.jl
- src/ADNLPProblems/hs233.jl
- src/ADNLPProblems/hs234.jl
- src/ADNLPProblems/hs235.jl
- src/Meta/hs231.jl
- src/Meta/hs232.jl
- src/Meta/hs233.jl
- src/Meta/hs234.jl
- src/Meta/hs235.jl
- src/PureJuMP/hs231.jl
- src/PureJuMP/hs232.jl
- src/PureJuMP/hs233.jl
- src/PureJuMP/hs234.jl
- src/PureJuMP/hs235.jl
> HS231 to 235

- Project.toml
fix broken 0..7.2 https://github.com/JuliaSmoothOptimizers/OptimizationProblems.jl/pull/307
> Version 0.7.3

- CITATION.bib
- CITATION.cff
- LICENSE.md
- README.md
- docs/src/index.md
@software{Migot_OptimizationProblems_jl_A_collection_2023,
author = {Migot, Tangi and Orban, Dominique and Soares Siqueira, Abel and contributors},
license = {MPL-2.0},
month = jul,
title = {{OptimizationProblems.jl: A collection of optimization problems in Julia}},
url = {https://github.com/JuliaSmoothOptimizers/OptimizationProblems.jl},
version = {0.7.3},
year = {2023}
}
> Add CITATION.cff

- docs/src/benchmark.md
Preview modified file: https://jso.dev/OptimizationProblems.jl/previews/PR323/benchmark/
> Add using ADNLPProblems in benchmark tutorial

- test/utils.jl
```
using OptimizationProblems, NLPModels, NLPModelsJuMP
include("test/utils.jl")
name = "glider"
open("$name.jl", "w") do io
print(io, generate_meta("$name"))
end
```
should now be possible to generate the Meta if we only have the JuMP model.
> Allow PureJuMP problems in generate meta

- .github/workflows/Breakage.yml
> Add breakage tests

- docs/Project.toml
- docs/make.jl
- docs/src/benchmark.md
> Support Documenter.jl v1.0

- src/ADNLPProblems/clplatea.jl
- src/ADNLPProblems/clplateb.jl
- src/ADNLPProblems/clplatec.jl
Resolves #355; tests are passing locally.
> Fix small dimension specification issue.
